### ISSUE TITLE
System.BadImageFormatException: 'Could not load file or assembly 'Telegram.Td'. An attempt was made to load a program with an incorrect format.'

### ISSUE THREAD

**Issue by Muaath5** [ph09nix/TDLibCore#2]
```
System.BadImageFormatException: 'Could not load file or assembly 'Telegram.Td, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.'
```
How can I fix it?
I included the TDLibCore using Nuget, I imported `Telegram.Td` in _References_
See photo:

![Files in my project](https://user-images.githubusercontent.com/60256639/110288496-28060700-7ff9-11eb-9ce6-2391030e6d1c.png)

**Comment by ph09nix** [comment]
make sure there is all dependancies in same folder
also disable '**Prefer 32 bit**' in your debug setting

**Comment by Muaath5** [comment]
> make sure there is all dependancies in same folder
> also disable '**Prefer 32 bit**' in your debug setting

`Prefer 32 bit` is `Disabled`.

Should I use .NET Framewrok?

**Comment by ph09nix** [comment]
you can use in either **.Net Core** or **.Net Framework**

**Comment by Muaath5** [comment]
I fixed the problem.
I understand that all DLLs should be in same folder that `app.exe` is in.
